// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6lFUAjSXqULJYwLWC_H2ShqbpRTQ_TZE',
    appId: '1:727349272492:web:578f656aa499d9a5c6e409',
    messagingSenderId: '727349272492',
    projectId: 'apt3065-5a3ea',
    authDomain: 'apt3065-5a3ea.firebaseapp.com',
    storageBucket: 'apt3065-5a3ea.appspot.com',
    measurementId: 'G-P862F2XD8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqApBL9-ydip-ePiOj63QW7PuJXqkGfg',
    appId: '1:727349272492:android:389962c32ae17afac6e409',
    messagingSenderId: '727349272492',
    projectId: 'apt3065-5a3ea',
    storageBucket: 'apt3065-5a3ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5-u3XLfODuAUJ5jyD7JTR_0uTbFbEaaE',
    appId: '1:727349272492:ios:a4f91eba62819a74c6e409',
    messagingSenderId: '727349272492',
    projectId: 'apt3065-5a3ea',
    storageBucket: 'apt3065-5a3ea.appspot.com',
    iosBundleId: 'com.example.apt3065',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5-u3XLfODuAUJ5jyD7JTR_0uTbFbEaaE',
    appId: '1:727349272492:ios:f62355c69cbb966ac6e409',
    messagingSenderId: '727349272492',
    projectId: 'apt3065-5a3ea',
    storageBucket: 'apt3065-5a3ea.appspot.com',
    iosBundleId: 'com.example.apt3065.RunnerTests',
  );
}
